//! Message module.

/// The role of the entity that generated a message.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum Role {
    /// System messages provide instructions and context to the model.
    System,
    /// User messages are the prompts provided by the user.
    #[default]
    User,
    /// Assistant messages are the responses generated by the model.
    Assistant,
    /// Tool messages provide the results of a tool call.
    Tool,
}

/// A single message in a conversation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Message {
    role: Role,
    content: String,
}

impl Message {
    /// Creates a new [`Message`] with the specified role and content.
    #[must_use]
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
        }
    }

    /// Returns the role of the message.
    #[must_use]
    pub fn role(&self) -> &Role {
        &self.role
    }

    /// Returns the content of the message.
    #[must_use]
    pub fn content(&self) -> &str {
        &self.content
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_creation() {
        let msg = Message::new(Role::User, "Hello");
        assert_eq!(*msg.role(), Role::User);
        assert_eq!(msg.content(), "Hello");
    }
}
