[workspace]
resolver = "2"
members = [
    "crates/jules-sdk",
    "crates/jules-core",
    "crates/jules-api",
    "crates/jules-macros",
    "crates/jules-cli",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
rust-version = "1.90.0"
authors = ["ArtisanXL"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ArtisanXL/jules-sdk"
homepage = "https://github.com/ArtisanXL/jules-sdk"
documentation = "https://docs.rs/jules-sdk"
description = "Early-stage (pre-alpha), async-first and idiomatic Rust implementation of Google's Jules SDK"

[workspace.lints.rust]
future-incompatible = { level = "warn", priority = -1 }
nonstandard-style = { level = "deny", priority = -2 }
rust_2018_idioms = { level = "deny", priority = -3 }
unused_variables = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = 10 }
redundant_clone = { level = "deny", priority = 9 }
pedantic = { level = "warn", priority = 3 }

[workspace.dependencies]
jules-sdk = { path = "crates/jules-sdk", version = "0.1.1" }
jules-core = { path = "crates/jules-core", version = "0.1.1" }
jules-api = { path = "crates/jules-api", version = "0.1.1" }
jules-macros = { path = "crates/jules-macros", version = "0.1.1" }
jules-cli = { path = "crates/jules-cli", version = "0.1.1" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
